DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS registHome;

CREATE TABLE client (id INT, name VARCHAR(250),password VARCHAR(250),username VARCHAR(250));

CREATE TABLE user(id INT, name VARCHAR(250), username VARCHAR(250),password VARCHAR(250));
