amazonProperties:
    endpointUrl: https://s3.us-east-2.amazonaws.com/
    accessKey: 
    secretKey: 
    bucketName: my-bucket-image-spring
    
spring:
    mail:
        default-encoding: UTF-8
        host: smtp-mail.outlook.com
        port: 587
        username: andreferreira6578@outlook.pt
        password: 
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true
        protocol: smtp
        test-connection: false
