amazonProperties:
    endpointUrl: https://s3.us-east-2.amazonaws.com/
    accessKey: AKIA5ROXX3QDJRF4UXO6
    secretKey: 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
    bucketName: my-bucket-image-spring
    
spring:
    mail:
        default-encoding: UTF-8
        host: smtp-mail.outlook.com
        port: 587
        username: andreferreira6578@outlook.pt
        password: Riotbuffoteupai123
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true
        protocol: smtp
        test-connection: false
