amazonProperties:
    endpointUrl: https://s3.us-east-2.amazonaws.com
    accessKey: AKIAU3LSQWSZF5FTKGD6
    secretKey: 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
    bucketName: spring-boot-imobiliaria-images-upload

spring:
    mail:
        default-encoding: UTF-8
        host: smtp-mail.outlook.com
        port: 587
        username: andre.ferreira@decode.pt	
        password: FEx#@6%Bd8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                debug: true
        protocol: smtp
        test-connection: false
