amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAU3LSQWSZF5FTKGD6
  secretKey: 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
  bucketName: spring-boot-imobiliaria-images-upload
