version: "3"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_DATABASE=imobiliaria
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sonarqube: 
    platform: linux/amd64
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=teste

volumes:
  mysql_data:
  sonarqube_data: