version: "3"
services:
  sonarqube: 
    platform: linux/amd64
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - sonarqubenet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    restart: on-failure

  db:
    image: postgres
    networks:
      - sonarqubenet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure
    container_name: postgresql
   
networks:
  sonarqubenet:
    driver: bridge

volumes:
  mysql_data:
  sonarqube_data: