version: "3"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=B7@,Nc`g-7Z:M/ZP
      - MYSQL_DATABASE=imobiliaria
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: B7@,Nc`g-7Z:M/ZP